services:
  webserver1:
    image: nginx
    container_name: example1-webserver
    restart: always
    volumes:
      - ./sites/example1.se/:/usr/share/nginx/html:ro
      - ./webservers/example1/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-net

  webserver2:
    image: nginx
    container_name: example2-webserver
    restart: always
    volumes:
      - ./sites/example2.se/:/usr/share/nginx/html:ro
      - ./webservers/example2/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-net

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./reverse-proxy/conf.d/:/etc/nginx/conf.d/:ro
      - certbot/www:/var/www/certbot/:ro
      - certbot/conf:/etc/nginx/ssl/:ro
    networks:
      - proxy-net

  certbot:
    depends_on:
      - reverse-proxy
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot/www:/var/www/certbot/:rw
      - certbot/conf:/etc/letsencrypt/:rw
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
    name: proxy-net

volumes:
  certbot:
  certs:
