services:
  webserver1:
    image: nginx
    container_name: webserver1
    restart: always
    volumes:
      - ./sites/example1.se/:/usr/share/nginx/html/
      - ./webservers/webserver1/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy-net

  webserver2:
    image: nginx
    container_name: webserver2
    restart: always
    volumes:
      - ./sites/example2.se/:/usr/share/nginx/html/
      - ./webservers/webserver2/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy-net

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./reverse-proxy/html/:/usr/share/nginx/html/
    networks:
      - proxy-net
    depends_on:
      - webserver1
      - webserver2

networks:
  proxy-net:
    driver: bridge
    name: proxy-net
