include:
  - ./services/service1/compose.yml
  - ./services/service2/compose.yml

services:
  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./reverse-proxy/sites-enabled/:/etc/nginx/conf.d/:ro
      - certbot:/var/www/certbot/:ro
      - certs:/etc/nginx/ssl/:ro
    networks:
      - webserver-net

  certbot:
    depends_on:
      - reverse-proxy
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot:/var/www/certbot/:rw
      - certs:/etc/letsencrypt/:rw
    networks:
      - webserver-net

networks:
  webserver-net:
    driver: bridge
    name: webserver-net

volumes:
  certbot:
  certs:
