services:
  example1-webserver:
    depends_on:
      - example1-php-fpm
    image: nginx
    container_name: example1-webserver
    restart: always
    volumes:
      - ./sites/example1/:/var/www/html/:ro
      - ./webservers/example1/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webserver-net

  altavision-php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    container_name: example1-php-fpm
    volumes:
      - ./sites/example1/:/var/www/html:ro
    networks:
      - webserver-net
