services:
  example2-webserver:
    image: nginx
    container_name: example2-webserver
    restart: always
    volumes:
      - ./sites/altavision/:/var/www/html/:ro
      - ./servers/altavision/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webserver-net
