services:
  example2-db:
    image: mariadb:10.11
    container_name: example2-db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - example2db:/var/lib/mysql
    networks:
      - example2-db-net

  example2-wordpress:
    depends_on:
      - example2-db
    image: wordpress:6.7.2-fpm
    container_name: example2-wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=example2-db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_CONFIG_EXTRA=
          define('WP_HOME','http://example2.com/');
          define('WP_SITEURL','http://example2.com/');
    volumes:
      - example2wp:/var/www/html:rw
    networks:
      - webserver-net
      - example2-db-net

  novatec-webserver:
    depends_on:
      - example2-wordpress
    image: nginx
    container_name: example2-webserver
    restart: always
    volumes:
      - example2wp:/var/www/html:ro
      - ./webservers/example2/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webserver-net

networks:
  example2-db-net:
    driver: bridge
    name: example2-db-net

volumes:
  example2db:
  example2wp:
