services:
  service1-webserver:
    depends_on:
      - service1-php-fpm
    image: nginx
    container_name: service1-webserver
    restart: always
    volumes:
      - ./public-html/:/var/www/html/:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webserver-net

  service1-php-fpm:
    build:
      context: ../../php-fpm
      dockerfile: Dockerfile
    container_name: service1-php-fpm
    volumes:
      - ./public-html/:/var/www/html:ro
    networks:
      - webserver-net
