services:
  service2-db:
    image: mariadb:latest
    container_name: service2-db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DB
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - service2db:/var/lib/mysql
    networks:
      - service2-db-net

  service2-wp:
    depends_on:
      - service2-db
    image: wordpress:6.8.1-fpm
    container_name: service2-wp
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=service2-db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DB
      - WORDPRESS_CONFIG_EXTRA=
            define('WP_HOME','${WP_HOME}');
            define('WP_SITEURL','${WP_SITEURL}');

    volumes:
      - service2wp:/var/www/html:rw
    networks:
      - webserver-net
      - service2-db-net

  service2-webserver:
    depends_on:
      - service2-wp
    image: nginx
    container_name: service2-webserver
    restart: unless-stopped
    volumes:
      - service2wp:/var/www/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webserver-net

networks:
  service2-db-net:
    driver: bridge
    name: service2-db-net

volumes:
  service2db:
  service2wp:
